#!/bin/sh
# Usage example: ./nix-update --argstr package oc.voodoops2

nixpkgs="$(nix-instantiate --eval --expr '<nixpkgs>')"
nix-shell $nixpkgs/maintainers/scripts/update.nix --arg include-overlays "(import ./. { }).overlays" $@
